services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: nhothoang/water-app-frontend:latest
    container_name: flask_app
    restart: unless-stopped
    shm_size: 2g
    ports:
      - "3699:3699"
    networks:
      - app_network
    env_file:
      - .env.prod
    volumes:
      - flask_app_data:/app/data
volumes:
  flask_app_data:
    name: flask_app_data
    driver: local
networks:
  app_network:
    driver: bridge
    external: true
