services:
  fastapi:
    image: nhothoang/water-app-backend:latest
    container_name: backend_water_app
    restart: unless-stopped
    shm_size: 2g
    ports:
      - "8001:8001"
    env_file:
      - .env
    networks:
      - app_network

volumes:
  backend_data:
    driver: local
networks:
  app_network:
    driver: bridge
    external: true
